#!/bin/bash
#depends on: imagemagick, i3lock, scrot

IMAGE=/tmp/lockscreen.png
TEXT=/tmp/locktext.png
ICON=$HOME/.i3/scripts/lock.png

scrot $IMAGE
#convert $IMAGE -scale 10% -scale 1000% -fill black -colorize 25% $IMAGE
convert $IMAGE -fill black -level 0%,100%,0.6 -filter Gaussian -resize 20% -define \
  filter:sigma=1.5 -resize 500.5% $IMAGE
[ -f $TEXT ] || {
  convert -size 1920x60 xc:white -font Liberation-Sans -pointsize 26 -fill black \
    -gravity center -annotate +0+0 'Type password to unlock' $TEXT;
  convert $TEXT -alpha set -channel A -evaluate set 50% $TEXT;
}
convert $IMAGE $TEXT -gravity center -geometry +0+200 -composite $IMAGE
convert $IMAGE $ICON -gravity center -composite -matte $IMAGE
i3lock --textcolor=ffffff00 --insidecolor=ffffff1c --ringcolor=ffffff3e \
--linecolor=ffffff00 --keyhlcolor=00000080 --ringvercolor=00000000 \
--separatorcolor=22222260 --insidevercolor=0000001c \
--ringwrongcolor=00000055 --insidewrongcolor=0000001c -i $IMAGE
