#!/usr/bin/perl

# File generated by menutray v0.45

# DO NOT edit this file!
# Any change in this file will be lost!
# Edit '/home/rhs/.config/menutray/schema.pl' instead!

use utf8;
use Gtk2 ('-init');

my $menu = 'Gtk2::Menu'->new;
my $icon = 'Gtk2::StatusIcon'->new;

$icon->set_from_icon_name('start-here');
$icon->set_visible(1);
$icon->signal_connect('button-release-event', \&show_icon_menu);

load_menu();

sub show_icon_menu {
    $menu->popup(undef, undef, sub {return Gtk2::StatusIcon::position_menu($menu, 0, 0, $icon)}, [1, 1], 0, 0);
    return 1;
}

sub load_menu {
{
    my $item = 'Gtk2::ImageMenuItem'->new("File\ Manager");
    $item->set_image('Gtk2::Image'->new_from_icon_name("file\-manager",q{menu}));
    $item->signal_connect('activate', sub {system "thunar &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("Terminal");
    $item->set_image('Gtk2::Image'->new_from_icon_name("terminal",q{menu}));
    $item->signal_connect('activate', sub {system "urxvt &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("Web\ Browser");
    $item->set_image('Gtk2::Image'->new_from_icon_name("web\-browser",q{menu}));
    $item->signal_connect('activate', sub {system "chromium &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("Run\ command");
    $item->set_image('Gtk2::Image'->new_from_icon_name("system\-run",q{menu}));
    $item->signal_connect('activate', sub {system "rofi\ \-show\ run &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("Instant\ messaging");
    $item->set_image('Gtk2::Image'->new_from_icon_name("system\-users",q{menu}));
    $item->signal_connect('activate', sub {system "pidgin &"});
    $menu->append($item);
}


    $menu->append('Gtk2::SeparatorMenuItem'->new);

    # # # # # # # # # # # # # # # # # # # # ACCESSORIES # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Accessories");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-utilities",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("About\ Xfce");
    $app->signal_connect('activate', sub {system "xfce4\-about &"});
    $app->set_property('tooltip_text', "Information\ about\ the\ Xfce\ Desktop\ Environment");
    $app->set_image('Gtk2::Image'->new_from_icon_name("help\-about",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Archive\ Manager");
    $app->signal_connect('activate', sub {system "file\-roller &"});
    $app->set_property('tooltip_text', "Create\ and\ modify\ an\ archive");
    $app->set_image('Gtk2::Image'->new_from_icon_name("file\-roller",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Bulk\ Rename");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/Thunar\/ThunarBulkRename &"});
    $app->set_property('tooltip_text', "Rename\ Multiple\ Files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("Thunar",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Catfish\ File\ Search");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/catfish &"});
    $app->set_property('tooltip_text', "Search\ the\ file\ system");
    $app->set_image('Gtk2::Image'->new_from_icon_name("catfish",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("compton");
    $app->signal_connect('activate', sub {system "compton &"});
    $app->set_property('tooltip_text', "A\ X\ compositor");
    $app->set_image('Gtk2::Image'->new_from_icon_name("compton",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Disks");
    $app->signal_connect('activate', sub {system "gnome\-disks &"});
    $app->set_property('tooltip_text', "Manage\ Drives\ and\ Media");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gnome\-disks",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("File\ Manager");
    $app->signal_connect('activate', sub {system "exo\-open\ \-\-launch\ FileManager &"});
    $app->set_property('tooltip_text', "Browse\ the\ file\ system");
    $app->set_image('Gtk2::Image'->new_from_icon_name("system\-file\-manager",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Galculator");
    $app->signal_connect('activate', sub {system "galculator &"});
    $app->set_property('tooltip_text', "Perform\ simple\ and\ scientific\ calculations");
    $app->set_image('Gtk2::Image'->new_from_icon_name("galculator",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Help");
    $app->signal_connect('activate', sub {system "yelp &"});
    $app->set_property('tooltip_text', "Get\ help\ with\ GNOME");
    $app->set_image('Gtk2::Image'->new_from_icon_name("help\-browser",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("HP\ Device\ Manager");
    $app->signal_connect('activate', sub {system "hp\-toolbox &"});
    $app->set_property('tooltip_text', "View\ device\ status\,\ ink\ levels\ and\ perform\ maintenance\.");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/hplip\/data\/images\/128x128\/hp_logo\.png",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Leafpad");
    $app->signal_connect('activate', sub {system "leafpad &"});
    $app->set_property('tooltip_text', "Simple\ text\ editor");
    $app->set_image('Gtk2::Image'->new_from_icon_name("leafpad",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("MasterPassword");
    $app->signal_connect('activate', sub {system "\"\/usr\/bin\/masterpassword\" &"});
    $app->set_property('tooltip_text', "A\ stateless\ password\ management\ solution");
    $app->set_image('Gtk2::Image'->new_from_icon_name("masterpassword",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Nemo");
    $app->signal_connect('activate', sub {system "nemo &"});
    $app->set_property('tooltip_text', "Access\ and\ organize\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("folder",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Peek");
    $app->signal_connect('activate', sub {system "peek &"});
    $app->set_property('tooltip_text', "An\ animated\ GIF\ recorder");
    $app->set_image('Gtk2::Image'->new_from_icon_name("peek",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Redshift");
    $app->signal_connect('activate', sub {system "redshift\-gtk &"});
    $app->set_property('tooltip_text', "Color\ temperature\ adjustment\ tool");
    $app->set_image('Gtk2::Image'->new_from_icon_name("redshift",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Rockbox\ Utility");
    $app->signal_connect('activate', sub {system "RockboxUtility &"});
    $app->set_property('tooltip_text', "Rockbox\ automated\ installer");
    $app->set_image('Gtk2::Image'->new_from_icon_name("rbutil",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Root\ Terminal");
    $app->signal_connect('activate', sub {system "gksu\ \-l\ gnome\-terminal &"});
    $app->set_property('tooltip_text', "Opens\ a\ terminal\ as\ the\ root\ user\,\ using\ gksu\ to\ ask\ for\ the\ password");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gksu\-root\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Terminal\ Emulator");
    $app->signal_connect('activate', sub {system "exo\-open\ \-\-launch\ TerminalEmulator &"});
    $app->set_property('tooltip_text', "Use\ the\ command\ line");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Thunar\ File\ Manager");
    $app->signal_connect('activate', sub {system "thunar &"});
    $app->set_property('tooltip_text', "Browse\ the\ filesystem\ with\ the\ file\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("Thunar",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # DEVELOPMENT # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Development");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-development",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("CMake");
    $app->signal_connect('activate', sub {system "cmake\-gui &"});
    $app->set_property('tooltip_text', "Cross\-platform\ buildsystem");
    $app->set_image('Gtk2::Image'->new_from_icon_name("CMakeSetup",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("DBeaver");
    $app->signal_connect('activate', sub {system "\/opt\/dbeaver\/dbeaver &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("dbeaver",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Devhelp");
    $app->signal_connect('activate', sub {system "devhelp &"});
    $app->set_property('tooltip_text', "Developer\'s\ Help\ program");
    $app->set_image('Gtk2::Image'->new_from_icon_name("devhelp",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("EAGLE\ Light\ Edition");
    $app->signal_connect('activate', sub {system "eagle &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("eagle",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("GHex");
    $app->signal_connect('activate', sub {system "ghex &"});
    $app->set_property('tooltip_text', "Inspect\ and\ edit\ binary\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("ghex",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Glade");
    $app->signal_connect('activate', sub {system "glade &"});
    $app->set_property('tooltip_text', "Create\ or\ open\ user\ interface\ designs\ for\ GTK\+\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("glade",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("MySQL\ Workbench");
    $app->signal_connect('activate', sub {system "mysql\-workbench &"});
    $app->set_property('tooltip_text', "MySQL\ Database\ Design\,\ Administration\ and\ Development\ Tool");
    $app->set_image('Gtk2::Image'->new_from_icon_name("mysql\-workbench",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("OpenJDK\ 1\.7\.0\ Policy\ Tool");
    $app->signal_connect('activate', sub {system "_BINDIR_\/policytool &"});
    $app->set_property('tooltip_text', "Manage\ OpenJDK\ policy\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("java\-1\.7\.0",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt4\ Assistant");
    $app->signal_connect('activate', sub {system "assistant\-qt4 &"});
    $app->set_property('tooltip_text', "Shows\ Qt4\ documentation\ and\ examples");
    $app->set_image('Gtk2::Image'->new_from_icon_name("assistant\-qt4",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt4\ Designer");
    $app->signal_connect('activate', sub {system "designer\-qt4 &"});
    $app->set_property('tooltip_text', "Design\ GUIs\ for\ Qt4\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("designer\-qt4",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt4\ Linguist");
    $app->signal_connect('activate', sub {system "linguist\-qt4 &"});
    $app->set_property('tooltip_text', "Add\ translations\ to\ Qt4\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("linguist\-qt4",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt4\ QDbusViewer");
    $app->signal_connect('activate', sub {system "qdbusviewer\-qt4 &"});
    $app->set_property('tooltip_text', "Debug\ D\-Bus\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("qdbusviewer\-qt4",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt\ Assistant");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/qt\/bin\/assistant &"});
    $app->set_property('tooltip_text', "Shows\ Qt\ documentation\ and\ examples");
    $app->set_image('Gtk2::Image'->new_from_icon_name("assistant",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt\ Creator");
    $app->signal_connect('activate', sub {system "qtcreator &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("QtProject\-qtcreator",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt\ Designer");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/qt\/bin\/designer &"});
    $app->set_property('tooltip_text', "Design\ GUIs\ for\ Qt\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("QtProject\-designer",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt\ Linguist");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/qt\/bin\/linguist &"});
    $app->set_property('tooltip_text', "Add\ translations\ to\ Qt\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("linguist",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt\ QDbusViewer");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/qt\/bin\/qdbusviewer &"});
    $app->set_property('tooltip_text', "Debug\ D\-Bus\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("qdbusviewer",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Sublime\ Text\ 3\ Dev");
    $app->signal_connect('activate', sub {system "subl3 &"});
    $app->set_property('tooltip_text', "Sophisticated\ text\ editor\ for\ code\,\ markup\ and\ prose");
    $app->set_image('Gtk2::Image'->new_from_icon_name("sublime\-text",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Zeal");
    $app->signal_connect('activate', sub {system "zeal &"});
    $app->set_property('tooltip_text', "Simple\ API\ documentation\ browser");
    $app->set_image('Gtk2::Image'->new_from_icon_name("zeal",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # EDUCATION # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Education");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-science",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Math");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-math &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ scientific\ formulas\ and\ equations\ by\ using\ Math\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-math",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # GAMES # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Games");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-games",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Linux\ Steam\ Integration");
    $app->signal_connect('activate', sub {system "lsi\-settings &"});
    $app->set_property('tooltip_text', "Application\ for\ managing\ Steam\ integration\ settings");
    $app->set_image('Gtk2::Image'->new_from_icon_name("steam",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("PlayOnLinux");
    $app->signal_connect('activate', sub {system "playonlinux &"});
    $app->set_property('tooltip_text', "PlayOnLinux");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/playonlinux\/etc\/playonlinux\.png",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Steam");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/steam &"});
    $app->set_property('tooltip_text', "Application\ for\ managing\ and\ playing\ games\ on\ Steam");
    $app->set_image('Gtk2::Image'->new_from_icon_name("steam",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # GRAPHICS # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Graphics");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-graphics",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Document\ Viewer");
    $app->signal_connect('activate', sub {system "evince &"});
    $app->set_property('tooltip_text', "View\ multi\-page\ documents");
    $app->set_image('Gtk2::Image'->new_from_icon_name("evince",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("FontForge");
    $app->signal_connect('activate', sub {system "fontforge &"});
    $app->set_property('tooltip_text', "An\ outline\ font\ editor");
    $app->set_image('Gtk2::Image'->new_from_icon_name("fontforge",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("gExtractWinIcons");
    $app->signal_connect('activate', sub {system "gextractwinicons &"});
    $app->set_property('tooltip_text', "A\ GTK\ utility\ to\ extract\ cursors\,\ icons\ and\ png\ image\ previews\ from\ MS\ Windows\ resource\ files\ \(like\ \.exe\,\ \.dll\,\ \.ocx\,\ \.cpl\)");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gextractwinicons",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("GNU\ Image\ Manipulation\ Program");
    $app->signal_connect('activate', sub {system "gimp\-2\.8 &"});
    $app->set_property('tooltip_text', "Create\ images\ and\ edit\ photographs");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gimp",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("gThumb");
    $app->signal_connect('activate', sub {system "gthumb &"});
    $app->set_property('tooltip_text', "View\ and\ organize\ your\ images");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gthumb",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("imgur\-screenshot");
    $app->signal_connect('activate', sub {system "imgur\-screenshot &"});
    $app->set_property('tooltip_text', "Upload\ the\ image\ to\ imgur\ web\ service");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/pixmaps\/imgur\-screenshot\.png",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Inkscape");
    $app->signal_connect('activate', sub {system "inkscape &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ Scalable\ Vector\ Graphics\ images");
    $app->set_image('Gtk2::Image'->new_from_icon_name("inkscape",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Draw");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-draw &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ drawings\,\ flow\ charts\ and\ logos\ by\ using\ Draw\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-draw",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Simple\ Scan");
    $app->signal_connect('activate', sub {system "simple\-scan &"});
    $app->set_property('tooltip_text', "Scan\ Documents");
    $app->set_image('Gtk2::Image'->new_from_icon_name("scanner",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # MULTIMEDIA # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Multimedia");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-multimedia",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Audacity");
    $app->signal_connect('activate', sub {system "env\ UBUNTU_MENUPROXY\=0\ audacity &"});
    $app->set_property('tooltip_text', "Record\ and\ edit\ audio\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("audacity",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Brasero");
    $app->signal_connect('activate', sub {system "brasero &"});
    $app->set_property('tooltip_text', "Create\ and\ copy\ CDs\ and\ DVDs");
    $app->set_image('Gtk2::Image'->new_from_icon_name("brasero",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Clementine");
    $app->signal_connect('activate', sub {system "clementine &"});
    $app->set_property('tooltip_text', "Plays\ music\ and\ last\.fm\ streams");
    $app->set_image('Gtk2::Image'->new_from_icon_name("clementine",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Clementine");
    $app->signal_connect('activate', sub {system "clementine &"});
    $app->set_property('tooltip_text', "Plays\ music\ and\ last\.fm\ streams");
    $app->set_image('Gtk2::Image'->new_from_icon_name("clementine",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("easyMP3Gain");
    $app->signal_connect('activate', sub {system "easymp3gain &"});
    $app->set_property('tooltip_text', "A\ GUI\ for\ mp3gain\,\ vorbisgain\ and\ aacgain");
    $app->set_image('Gtk2::Image'->new_from_icon_name("easymp3gain",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Filebot");
    $app->signal_connect('activate', sub {system "filebot &"});
    $app->set_property('tooltip_text', "TV\ renamer\/subtitle\ downloader\/sfv\ validator");
    $app->set_image('Gtk2::Image'->new_from_icon_name("filebot",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Livestreamer\ Twitch\ GUI");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/livestreamer\-twitch\-gui &"});
    $app->set_property('tooltip_text', "Browse\ Twitch\.tv\ and\ watch\ streams\ in\ your\ videoplayer\ of\ choice");
    $app->set_image('Gtk2::Image'->new_from_icon_name("livestreamer\-twitch\-gui",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Livestreamer\ Twitch\ GUI");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/livestreamer\-twitch\-gui &"});
    $app->set_property('tooltip_text', "Browse\ Twitch\.tv\ and\ watch\ streams\ in\ your\ videoplayer\ of\ choice");
    $app->set_image('Gtk2::Image'->new_from_icon_name("livestreamer\-twitch\-gui",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Mp3tag");
    $app->signal_connect('activate', sub {system "mp3tag &"});
    $app->set_property('tooltip_text', "The\ universal\ tag\ editor");
    $app->set_image('Gtk2::Image'->new_from_icon_name("mp3tag",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("mpv\ Media\ Player");
    $app->signal_connect('activate', sub {system "mpv\ \-\-profile\=pseudo\-gui\ \-\- &"});
    $app->set_property('tooltip_text', "Play\ movies\ and\ songs");
    $app->set_image('Gtk2::Image'->new_from_icon_name("mpv",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Pithos");
    $app->signal_connect('activate', sub {system "pithos &"});
    $app->set_property('tooltip_text', "Play\ music\ from\ Pandora\ Radio");
    $app->set_image('Gtk2::Image'->new_from_icon_name("pithos",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Popcorn\ Time\ CE");
    $app->signal_connect('activate', sub {system "popcorntime\-ce &"});
    $app->set_property('tooltip_text', "Watch\ Movies\ and\ TV\ Shows\ instantly");
    $app->set_image('Gtk2::Image'->new_from_icon_name("popcorntime\-ce",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("PulseAudio\ Volume\ Control");
    $app->signal_connect('activate', sub {system "pavucontrol &"});
    $app->set_property('tooltip_text', "Adjust\ the\ volume\ level");
    $app->set_image('Gtk2::Image'->new_from_icon_name("multimedia\-volume\-control",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt\ V4L2\ test\ Utility");
    $app->signal_connect('activate', sub {system "qv4l2 &"});
    $app->set_property('tooltip_text', "Allow\ testing\ Video4Linux\ devices");
    $app->set_image('Gtk2::Image'->new_from_icon_name("qv4l2",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("SMPlayer");
    $app->signal_connect('activate', sub {system "smplayer &"});
    $app->set_property('tooltip_text', "A\ great\ MPlayer\ front\-end");
    $app->set_image('Gtk2::Image'->new_from_icon_name("smplayer",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("SMTube");
    $app->signal_connect('activate', sub {system "smtube &"});
    $app->set_property('tooltip_text', "Browse\ and\ search\ videos\ from\ YouTube");
    $app->set_image('Gtk2::Image'->new_from_icon_name("smtube",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Sound\ Converter");
    $app->signal_connect('activate', sub {system "soundconverter &"});
    $app->set_property('tooltip_text', "Converts\ audio\ files\ into\ other\ formats");
    $app->set_image('Gtk2::Image'->new_from_icon_name("soundconverter",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Spek");
    $app->signal_connect('activate', sub {system "spek &"});
    $app->set_property('tooltip_text', "View\ spectrograms\ of\ your\ audio\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("spek",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Spotify");
    $app->signal_connect('activate', sub {system "spotify &"});
    $app->set_property('tooltip_text', "Spotify\ streaming\ music\ client");
    $app->set_image('Gtk2::Image'->new_from_icon_name("spotify\-client",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("traGtor");
    $app->signal_connect('activate', sub {system "tragtor &"});
    $app->set_property('tooltip_text', "traGtor\ \-\ a\ GUI\ for\ FFmpeg\ for\ audio\ and\ video\-conversion");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/pixmaps\/tragtor\.svg",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("VLC\ media\ player");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/vlc\ \-\-started\-from\-file &"});
    $app->set_property('tooltip_text', "Read\,\ capture\,\ broadcast\ your\ multimedia\ streams");
    $app->set_image('Gtk2::Image'->new_from_icon_name("vlc",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # NETWORK # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Network");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-internet",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Avahi\ SSH\ Server\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/bssh &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\-enabled\ SSH\ Servers");
    $app->set_image('Gtk2::Image'->new_from_icon_name("network\-wired",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Avahi\ VNC\ Server\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/bvnc &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\-enabled\ VNC\ Servers");
    $app->set_image('Gtk2::Image'->new_from_icon_name("network\-wired",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Chromium");
    $app->signal_connect('activate', sub {system "chromium &"});
    $app->set_property('tooltip_text', "Access\ the\ Internet");
    $app->set_image('Gtk2::Image'->new_from_icon_name("chromium",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Firefox");
    $app->signal_connect('activate', sub {system "firefox &"});
    $app->set_property('tooltip_text', "Browse\ the\ World\ Wide\ Web");
    $app->set_image('Gtk2::Image'->new_from_icon_name("firefox",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("imgur\-screenshot");
    $app->signal_connect('activate', sub {system "imgur\-screenshot &"});
    $app->set_property('tooltip_text', "Upload\ the\ image\ to\ imgur\ web\ service");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/pixmaps\/imgur\-screenshot\.png",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Liferea");
    $app->signal_connect('activate', sub {system "liferea &"});
    $app->set_property('tooltip_text', "Read\ news\ feeds\ and\ blogs");
    $app->set_image('Gtk2::Image'->new_from_icon_name("liferea",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Linux\ Steam\ Integration");
    $app->signal_connect('activate', sub {system "lsi\-settings &"});
    $app->set_property('tooltip_text', "Application\ for\ managing\ Steam\ integration\ settings");
    $app->set_image('Gtk2::Image'->new_from_icon_name("steam",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Mail\ Reader");
    $app->signal_connect('activate', sub {system "exo\-open\ \-\-launch\ MailReader &"});
    $app->set_property('tooltip_text', "Read\ your\ email");
    $app->set_image('Gtk2::Image'->new_from_icon_name("internet\-mail",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Popcorn\ Time\ CE");
    $app->signal_connect('activate', sub {system "popcorntime\-ce &"});
    $app->set_property('tooltip_text', "Watch\ Movies\ and\ TV\ Shows\ instantly");
    $app->set_image('Gtk2::Image'->new_from_icon_name("popcorntime\-ce",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("qBittorrent");
    $app->signal_connect('activate', sub {system "qbittorrent &"});
    $app->set_property('tooltip_text', "Download\ and\ share\ files\ over\ BitTorrent");
    $app->set_image('Gtk2::Image'->new_from_icon_name("qbittorrent",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Skype");
    $app->signal_connect('activate', sub {system "skype &"});
    $app->set_property('tooltip_text', "Skype\ Internet\ Telephony");
    $app->set_image('Gtk2::Image'->new_from_icon_name("skype",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Steam");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/steam &"});
    $app->set_property('tooltip_text', "Application\ for\ managing\ and\ playing\ games\ on\ Steam");
    $app->set_image('Gtk2::Image'->new_from_icon_name("steam",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Syncthing\ GTK");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/syncthing\-gtk &"});
    $app->set_property('tooltip_text', "GUI\ for\ Syncthing");
    $app->set_image('Gtk2::Image'->new_from_icon_name("syncthing\-gtk",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("TeamSpeak\ 3");
    $app->signal_connect('activate', sub {system "teamspeak3 &"});
    $app->set_property('tooltip_text', "TeamSpeak\ is\ software\ for\ quality\ voice\ communication\ via\ the\ Internet");
    $app->set_image('Gtk2::Image'->new_from_icon_name("teamspeak3",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Tor\-Browser\ \(en\-US\)");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/tor\-browser\-en &"});
    $app->set_property('tooltip_text', "Tor\ Browser\ Bundle\:\ Anonymous\ browsing\ using\ firefox\ and\ tor");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/pixmaps\/tor\-browser\-en\.png",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Web\ Browser");
    $app->signal_connect('activate', sub {system "exo\-open\ \-\-launch\ WebBrowser &"});
    $app->set_property('tooltip_text', "Browse\ the\ web");
    $app->set_image('Gtk2::Image'->new_from_icon_name("web\-browser",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Zenmap");
    $app->signal_connect('activate', sub {system "zenmap &"});
    $app->set_property('tooltip_text', "A\ cross\-platform\ GUI\ for\ the\ Nmap\ Security\ Scanner\.");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/zenmap\/pixmaps\/zenmap\.png",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Zenmap\ \(as\ root\)");
    $app->signal_connect('activate', sub {system "\/usr\/share\/zenmap\/su\-to\-zenmap\.sh &"});
    $app->set_property('tooltip_text', "A\ cross\-platform\ GUI\ for\ the\ Nmap\ Security\ Scanner\.");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/zenmap\/pixmaps\/zenmap\.png",16,16)));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # OFFICE # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Office");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-office",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Document\ Viewer");
    $app->signal_connect('activate', sub {system "evince &"});
    $app->set_property('tooltip_text', "View\ multi\-page\ documents");
    $app->set_image('Gtk2::Image'->new_from_icon_name("evince",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Gummi");
    $app->signal_connect('activate', sub {system "gummi &"});
    $app->set_property('tooltip_text', "Simple\ LaTeX\ Editor");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gummi",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("JabRef");
    $app->signal_connect('activate', sub {system "jabref &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("jabref",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice");
    $app->signal_connect('activate', sub {system "libreoffice &"});
    $app->set_property('tooltip_text', "The\ office\ productivity\ suite\ compatible\ to\ the\ open\ and\ standardized\ ODF\ document\ format\.\ Supported\ by\ The\ Document\ Foundation\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-startcenter",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Base");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-base &"});
    $app->set_property('tooltip_text', "Manage\ databases\,\ create\ queries\ and\ reports\ to\ track\ and\ manage\ your\ information\ by\ using\ Base\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-base",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Calc");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-calc &"});
    $app->set_property('tooltip_text', "Perform\ calculations\,\ analyze\ information\ and\ manage\ lists\ in\ spreadsheets\ by\ using\ Calc\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-calc",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Draw");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-draw &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ drawings\,\ flow\ charts\ and\ logos\ by\ using\ Draw\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-draw",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Impress");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-impress &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ presentations\ for\ slideshows\,\ meeting\ and\ Web\ pages\ by\ using\ Impress\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-impress",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Math");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-math &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ scientific\ formulas\ and\ equations\ by\ using\ Math\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-math",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Writer");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-writer &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ text\ and\ graphics\ in\ letters\,\ reports\,\ documents\ and\ Web\ pages\ by\ using\ Writer\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-writer",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Master\ PDF\ Editor");
    $app->signal_connect('activate', sub {system "\/opt\/masterpdfeditor\/masterpdfeditor3 &"});
    $app->set_property('tooltip_text', "Edit\ your\ PDF\ and\ XPS\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("pdfeditor",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Zathura");
    $app->signal_connect('activate', sub {system "zathura &"});
    $app->set_property('tooltip_text', "A\ minimalistic\ document\ viewer");
    $app->set_image('Gtk2::Image'->new_from_icon_name("zathura",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # SETTINGS # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Settings");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-accessories",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Accessibility");
    $app->signal_connect('activate', sub {system "xfce4\-accessibility\-settings &"});
    $app->set_property('tooltip_text', "Improve\ keyboard\ and\ mouse\ accessibility");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-accessibility",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Appearance");
    $app->signal_connect('activate', sub {system "xfce4\-appearance\-settings &"});
    $app->set_property('tooltip_text', "Customize\ the\ look\ of\ your\ desktop");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-theme",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("ARandR");
    $app->signal_connect('activate', sub {system "arandr &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("display",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Bluetooth\ Adapters");
    $app->signal_connect('activate', sub {system "blueman\-adapters &"});
    $app->set_property('tooltip_text', "Set\ Bluetooth\ Adapter\ Properties");
    $app->set_image('Gtk2::Image'->new_from_icon_name("blueman\-device",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Bluetooth\ Manager");
    $app->signal_connect('activate', sub {system "blueman\-manager &"});
    $app->set_property('tooltip_text', "Blueman\ Bluetooth\ Manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("blueman",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Customize\ Look\ and\ Feel");
    $app->signal_connect('activate', sub {system "lxappearance &"});
    $app->set_property('tooltip_text', "Customizes\ look\ and\ feel\ of\ your\ desktop\ and\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-theme",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Display");
    $app->signal_connect('activate', sub {system "xfce4\-display\-settings &"});
    $app->set_property('tooltip_text', "Configure\ screen\ settings\ and\ layout");
    $app->set_image('Gtk2::Image'->new_from_icon_name("video\-display",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("File\ Manager");
    $app->signal_connect('activate', sub {system "thunar\-settings &"});
    $app->set_property('tooltip_text', "Configure\ the\ Thunar\ file\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("system\-file\-manager",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Firewall\ Configuration");
    $app->signal_connect('activate', sub {system "gufw &"});
    $app->set_property('tooltip_text', "An\ easy\ way\ to\ configure\ your\ firewall");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gufw",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Keyboard");
    $app->signal_connect('activate', sub {system "xfce4\-keyboard\-settings &"});
    $app->set_property('tooltip_text', "Edit\ keyboard\ settings\ and\ application\ shortcuts");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-keyboard",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Linux\ Steam\ Integration");
    $app->signal_connect('activate', sub {system "lsi\-settings &"});
    $app->set_property('tooltip_text', "Application\ for\ managing\ Steam\ integration\ settings");
    $app->set_image('Gtk2::Image'->new_from_icon_name("steam",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("MIME\ Type\ Editor");
    $app->signal_connect('activate', sub {system "xfce4\-mime\-settings &"});
    $app->set_property('tooltip_text', "Associate\ applications\ with\ MIME\ types");
    $app->set_image('Gtk2::Image'->new_from_icon_name("application\-x\-executable",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Mouse\ and\ Touchpad");
    $app->signal_connect('activate', sub {system "xfce4\-mouse\-settings &"});
    $app->set_property('tooltip_text', "Configure\ pointer\ device\ behavior\ and\ appearance");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-peripherals",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Network\ Connections");
    $app->signal_connect('activate', sub {system "nm\-connection\-editor &"});
    $app->set_property('tooltip_text', "Manage\ and\ change\ your\ network\ connection\ settings");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-system\-network",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("NVIDIA\ X\ Server\ Settings");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/nvidia\-settings &"});
    $app->set_property('tooltip_text', "Configure\ NVIDIA\ X\ Server\ Settings");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/pixmaps\/nvidia\-settings\.png",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Panel");
    $app->signal_connect('activate', sub {system "xfce4\-panel\ \-\-preferences &"});
    $app->set_property('tooltip_text', "Customize\ the\ panel");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xfce4\-panel",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Preferred\ Applications");
    $app->signal_connect('activate', sub {system "exo\-preferred\-applications &"});
    $app->set_property('tooltip_text', "Preferred\ Applications\ \(Web\ Browser\,\ Mail\ Reader\ and\ Terminal\ Emulator\)");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-default\-applications",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Print\ Settings");
    $app->signal_connect('activate', sub {system "system\-config\-printer &"});
    $app->set_property('tooltip_text', "Configure\ printers");
    $app->set_image('Gtk2::Image'->new_from_icon_name("printer",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Privilege\ granting");
    $app->signal_connect('activate', sub {system "gksu\-properties &"});
    $app->set_property('tooltip_text', "Configure\ behavior\ of\ the\ privilege\-granting\ tool");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gksu",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Removable\ Drives\ and\ Media");
    $app->signal_connect('activate', sub {system "thunar\-volman\-settings &"});
    $app->set_property('tooltip_text', "Configure\ management\ of\ removable\ drives\ and\ media");
    $app->set_image('Gtk2::Image'->new_from_icon_name("drive\-removable\-media",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Settings\ Editor");
    $app->signal_connect('activate', sub {system "xfce4\-settings\-editor &"});
    $app->set_property('tooltip_text', "Graphical\ settings\ editor\ for\ Xfconf");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-system",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Settings\ Manager");
    $app->signal_connect('activate', sub {system "xfce4\-settings\-manager &"});
    $app->set_property('tooltip_text', "Graphical\ Settings\ Manager\ for\ Xfce\ 4");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # SYSTEM # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("System");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-system",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("AQEMU");
    $app->signal_connect('activate', sub {system "aqemu &"});
    $app->set_property('tooltip_text', "Virtual\ machine\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("aqemu",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Avahi\ Zeroconf\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/avahi\-discover &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\ services\ available\ on\ your\ network");
    $app->set_image('Gtk2::Image'->new_from_icon_name("network\-wired",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Bulk\ Rename");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/Thunar\/ThunarBulkRename &"});
    $app->set_property('tooltip_text', "Rename\ Multiple\ Files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("Thunar",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("CPU\-G");
    $app->signal_connect('activate', sub {system "cpu\-g &"});
    $app->set_property('tooltip_text', "CPU\-G\ collects\ and\ displays\ information\ about\ your\ CPU\,\ RAM\,\ Motherboard");
    $app->set_image('Gtk2::Image'->new_from_icon_name("cpu\-g",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("dconf\ Editor");
    $app->signal_connect('activate', sub {system "dconf\-editor &"});
    $app->set_property('tooltip_text', "Directly\ edit\ your\ entire\ configuration\ database");
    $app->set_image('Gtk2::Image'->new_from_icon_name("dconf\-editor",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Firestarter");
    $app->signal_connect('activate', sub {system "gksu\ firestarter &"});
    $app->set_property('tooltip_text', "Desktop\ Firewall\ Tool");
    $app->set_image('Gtk2::Image'->new_from_icon_name("firestarter",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("GNOME\ System\ Monitor");
    $app->signal_connect('activate', sub {system "gnome\-system\-monitor &"});
    $app->set_property('tooltip_text', "View\ current\ processes\ and\ monitor\ system\ state");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-system\-monitor",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("GParted");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/gparted_polkit &"});
    $app->set_property('tooltip_text', "Create\,\ reorganize\,\ and\ delete\ partitions");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gparted",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Htop");
    $app->signal_connect('activate', sub {system "termite\ \-e\ \'htop\' &"});
    $app->set_property('tooltip_text', "Show\ System\ Processes");
    $app->set_image('Gtk2::Image'->new_from_icon_name("htop",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Manage\ Printing");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/xdg\-open\ http\:\/\/localhost\:631\/ &"});
    $app->set_property('tooltip_text', "CUPS\ Web\ Interface");
    $app->set_image('Gtk2::Image'->new_from_icon_name("cups",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Oracle\ VM\ VirtualBox");
    $app->signal_connect('activate', sub {system "VirtualBox &"});
    $app->set_property('tooltip_text', "Run\ several\ virtual\ systems\ on\ a\ single\ host\ computer");
    $app->set_image('Gtk2::Image'->new_from_icon_name("virtualbox",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Power\ Statistics");
    $app->signal_connect('activate', sub {system "gnome\-power\-statistics &"});
    $app->set_property('tooltip_text', "Observe\ power\ management");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gnome\-power\-statistics",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Print\ Settings");
    $app->signal_connect('activate', sub {system "system\-config\-printer &"});
    $app->set_property('tooltip_text', "Configure\ printers");
    $app->set_image('Gtk2::Image'->new_from_icon_name("printer",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("ranger");
    $app->signal_connect('activate', sub {system "termite\ \-e\ \'ranger\' &"});
    $app->set_property('tooltip_text', "Launches\ the\ ranger\ file\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("System\ Monitor");
    $app->signal_connect('activate', sub {system "gnome\-system\-monitor &"});
    $app->set_property('tooltip_text', "View\ current\ processes\ and\ monitor\ system\ state");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-system\-monitor",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Terminal");
    $app->signal_connect('activate', sub {system "gnome\-terminal &"});
    $app->set_property('tooltip_text', "Use\ the\ command\ line");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Termite");
    $app->signal_connect('activate', sub {system "termite &"});
    $app->set_property('tooltip_text', "Use\ the\ command\ line");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Thunar\ File\ Manager");
    $app->signal_connect('activate', sub {system "thunar &"});
    $app->set_property('tooltip_text', "Browse\ the\ filesystem\ with\ the\ file\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("Thunar",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("urxvt");
    $app->signal_connect('activate', sub {system "urxvt &"});
    $app->set_property('tooltip_text', "An\ unicode\ capable\ rxvt\ clone");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("urxvt\ \(client\)");
    $app->signal_connect('activate', sub {system "urxvtc &"});
    $app->set_property('tooltip_text', "An\ unicode\ capable\ rxvt\ clone\ client\ for\ urxvtd");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("urxvt\ \(tabbed\)");
    $app->signal_connect('activate', sub {system "urxvt\-tabbed &"});
    $app->set_property('tooltip_text', "An\ unicode\ capable\ and\ tabbed\ rxvt\ clone");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("UXTerm");
    $app->signal_connect('activate', sub {system "uxterm &"});
    $app->set_property('tooltip_text', "standard\ terminal\ emulator\ for\ the\ X\ window\ system");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xterm\-color_48x48",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Wireshark");
    $app->signal_connect('activate', sub {system "wireshark &"});
    $app->set_property('tooltip_text', "Network\ traffic\ analyzer");
    $app->set_image('Gtk2::Image'->new_from_icon_name("wireshark",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("XTerm");
    $app->signal_connect('activate', sub {system "xterm &"});
    $app->set_property('tooltip_text', "standard\ terminal\ emulator\ for\ the\ X\ window\ system");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xterm\-color_48x48",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # MENUTRAY # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Menutray");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Config");
    $app->signal_connect('activate', sub {system "termite\ \-e\ \'\%s\'\ \/home\/rhs\/\.config\/menutray\/config\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ configuration\ file");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Menu");
    $app->signal_connect('activate', sub {system "termite\ \-e\ \'\%s\'\ \/home\/rhs\/\.config\/menutray\/menu\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ menu\ file\ for\ inspection");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Schema");
    $app->signal_connect('activate', sub {system "termite\ \-e\ \'\%s\'\ \/home\/rhs\/\.config\/menutray\/schema\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ schema\ file\ to\ customize\ the\ menu");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    $menu->append('Gtk2::SeparatorMenuItem'->new);
{
    my $regenerate = 'Gtk2::ImageMenuItem'->new("Regenerate");
    $regenerate->set_property('tooltip_text', "Regenerate\ this\ menu\.");
    $regenerate->set_image('Gtk2::Image'->new_from_icon_name("gtk\-refresh",q{menu}));
    $regenerate->signal_connect('activate', sub {system "\/usr\/bin\/perl\ \\\/usr\\\/bin\\\/menutray\ \-i &"; 'Gtk2'->main_quit});
    $menu->append($regenerate);
}
{
    my $quit = 'Gtk2::ImageMenuItem'->new("Exit");
    $quit->set_property('tooltip_text', "Close\ this\ application\.");
    $quit->set_image('Gtk2::Image'->new_from_icon_name("exit",q{menu}));
    $quit->signal_connect('activate', sub { Gtk2->main_quit });
    $menu->append($quit);
}
    $menu->show_all;
    return 1;
}
'Gtk2'->main;
