#!/bin/bash

full=""
short=""
status=0

URL='http://www.accuweather.com/en/lv/riga/225780/current-weather/225780';
SITE="$(curl -s "$URL")"
FETCH_STATUS=$?;

if [ $FETCH_STATUS -ne "0" -o -z "${SITE}" ]; then
  full="N/A";
  short="${full}";
  status=0;
else
  weather="$(echo "$SITE" | awk -F\' '/acm_RecentLocationsCarousel\.push/{print $14 }'| head -1)"
  daytime="$(echo "$SITE" | awk -F\' '/acm_RecentLocationsCarousel\.push/{print $2 }'| head -1)"
  temp="$(echo "$SITE" | awk -F\' '/acm_RecentLocationsCarousel\.push/{print $10"°" }'| head -1)"
  feel_temp="$(echo "$SITE" | awk -F\' '/acm_RecentLocationsCarousel\.push/{print $12"°" }'| head -1)"


  if [[ $weather == *thunder* || $weather == *Thunder* ]]; then
    icon=""
  else
    if [[ $weather == *rain* || $weather == *Rain* ]]; then
      icon=""
    else
      if [[ $weather == *cloud* || $weather == *Cloud* ]]; then
        icon=""
      else
        if [[ $weather == *snow* || $weather == *Snow* ]]; then
          icon=""
        else
          if [[ $daytime == *night* || $daytime == *Night* ]]; then
            icon=""
          else
            icon=""
          fi
        fi
      fi
    fi
  fi

  full="$icon $feel_temp"
  short="$temp"
fi;

echo -e $full
echo -e $short
echo $color;
exit $status
